# Generated by Django 5.0.2 on 2024-02-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DonationApp', '0002_volunteer_donor_address_donor_contact_donor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='userpic',
            new_name='donorpic',
        ),
    ]
