# Generated by Django 5.0.2 on 2024-02-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationApp', '0005_donor_email_donor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donorpic',
            field=models.FileField(null=True, upload_to='donorpic/'),
        ),
    ]
