# Generated by Django 4.2.5 on 2024-03-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DonationApp', '0009_volunteer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
    ]
